import powerfactory as pf
import itertools
import heapq
import csv
import os
import math
import matplotlib.pyplot as plt
import re  
import numpy as np 
from pathlib import Path

# === PowerFactory Initialization ===
app = pf.GetApplication()
app.ClearOutputWindow()

# === Parameter configuration ===
MIN_VOLTAGE = 0.9  # Minimum voltage threshold (p.u.)
P_STEP = 20  # Power step in MW
P_MAX = 400  # Maximum power per generator in MW
Z_THRESHOLD = 0.1  # Impedance threshold


# === Number of points to extract ===
NUM_POINTS = 70  # Start with a few points for testing

# === CRITICAL KNOWN POINT - YOU MUST FIND ONE FOR YOUR SYSTEM ===
KNOWN_POINT = {"P1_MW": 1, "P2_MW": 1183}  # P1=1MW, P2=425MW da U=0.9
# Opposite point (this will be the end of the sweep)
OPPOSITE_POINT = {"P1_MW": 770, "P2_MW": 1}  # P1=425MW, P2=1MW

# ------------------------------------------------------------
# RUTES
# ------------------------------------------------------------

# Repository root
REPO_ROOT = Path(__file__).resolve().parents[2]

# Example to be processed
EXAMPLE = "IEEE39"

# ------------------------------------------------------------
# INPUT
# File generated by find_electrically_close_nodes.py
# ------------------------------------------------------------
Z_IMPORT_PATH = (REPO_ROOT / "data" / "example" / EXAMPLE / "pares_nodos_cercanos.csv")

# ------------------------------------------------------------
# OUTPUT
# Folder where sweep results will be saved
# ------------------------------------------------------------

SCENARIO = EXAMPLE + "C" #Generation tipe
EXPORT_PATH = (REPO_ROOT / "data" / "results" / EXAMPLE / SCENARIO)

# Create results folder if it does not exist
EXPORT_PATH.mkdir(parents=True, exist_ok=True)

# Display paths for verification
print(f"📌 Ejemplo: {EXAMPLE}")
print(f"📥 Entrada: {Z_IMPORT_PATH}")
print(f"📤 Salida:  {EXPORT_PATH}")

##############################################################
impedance_data = {}

try:
    with open(Z_IMPORT_PATH, 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            nodo_i = row['Nodo_i']
            nodo_j = row['Nodo_j']
            zij = float(row['|Zij/zjj|'])
            impedance_data[(nodo_i, nodo_j)] = zij
            impedance_data[(nodo_j, nodo_i)] = zij
            
    app.PrintInfo(f"Impedance data loaded: {len(impedance_data)//2} node pairs")
except Exception as e:
    app.PrintError(f"Error loading impedance file: {str(e)}")
    raise SystemExit

# === Function to verify voltage trend ===
def check_voltage_trend(current_voltage, previous_voltage, current_power, previous_power, threshold=0.001):
    """
    Check the voltage vs. power trend.
    
    Returns:
        tuple: (is_anomaly, anomaly_type, message)
    """
    if previous_voltage is None or previous_power is None:
        return False, None, ""
    
    power_diff = current_power - previous_power
    voltage_diff = current_voltage - previous_voltage
    
    # Expected behavior: as power increases, voltage should decrease
    if power_diff > 0:
        # If the tension increases when it should decrease
        if voltage_diff > threshold:
            return True, "increasing", f"Voltage increased by {voltage_diff:.6f} p.u. with the increase in power"
        # If the tension remains constant
        elif abs(voltage_diff) < threshold:
            return True, "flat", f"Constant voltage with increased power"
    
    return False, None, ""

# === Identification of generators ===
sync_types = ["ElmSym"]
nonsync_types = ["ElmAsy", "ElmGenstat", "ElmPvsys", "ElmGenpv"]

gen_sync = []
gen_nonsync = []

for gtype in sync_types:
    gens = app.GetCalcRelevantObjects(f"*.{gtype}")
    if gens:
        gen_sync.extend([g for g in gens if hasattr(g, 'outserv') and g.outserv == 0])

for gtype in nonsync_types:
    gens = app.GetCalcRelevantObjects(f"*.{gtype}")
    if gens:
        gen_nonsync.extend([g for g in gens if hasattr(g, 'outserv') and g.outserv == 0])

app.PrintInfo(f"Synchronous generators found (in service): {len(gen_sync)}")
app.PrintInfo(f"Non-synchronous generators found (in service): {len(gen_nonsync)}")

if not gen_nonsync:
    app.PrintError("No non-synchronous generators (in service) were found. Check the generator types.")
    raise SystemExit

# Save base page for restoration
pgini_base = {g: g.pgini for g in gen_nonsync}

# === Function to extract the number from the bus name ===
def extract_bus_number(bus_name):
    """Extract the number from the bus name (ej: 'Bus 4' → '4', '4' → '4')"""
    # Search for digits in the name
    numbers = re.findall(r'\d+', bus_name)
    if numbers:
        return numbers[0]  # Return the first number found
    return bus_name  # If there are no numbers, return the original name

# === Function to determine the evaluation node for a generator ===
def get_evaluation_bus_for_generator(generator):
    """
    Determine the appropriate node to evaluate the generator impedance.
    
    """
    try:
        # Obtain the generator's direct connection bus
        gen_bus = generator.bus1.cterm if hasattr(generator, 'bus1') and generator.bus1.cterm else None
        
        if not gen_bus:
            app.PrintWarn(f"No bus could be obtained for {generator.loc_name}")
            return None
        
        # Search for transformers connected to this bus
        transformers = app.GetCalcRelevantObjects("*.ElmTr2") or []
        transformers.extend(app.GetCalcRelevantObjects("*.ElmTrf") or [])
        
        for trafo in transformers:
            # Verify whether the transformer is connected to the generator bus
            if (hasattr(trafo, 'bushv') and hasattr(trafo, 'buslv')):
                # Case 1: Generator on the LV side, transformer connected to the grid on the HV side
                if trafo.buslv.cterm == gen_bus:
                    # Verify whether the transformer name follows the expected pattern
                    trafo_name = trafo.loc_name.lower()
                    gen_name = generator.loc_name.lower()
                    
                    # Search for name matches (example: "TR PV1" y "PV1")
                    if ('tr' in trafo_name and any(word in trafo_name for word in ['pv', 'wind', 'gen']) and
                        any(word in gen_name for word in ['pv', 'wind', 'gen'])):
                        app.PrintInfo(f"Generator {generator.loc_name} connected via a transformer {trafo.loc_name} (LV→HV)")
                        return trafo.bushv.cterm.loc_name
                
                # Case 2: Generator on the HV side (less common direct connection)
                elif trafo.bushv.cterm == gen_bus:
                    app.PrintInfo(f"Generator {generator.loc_name} connected to the HV side of the transformer {trafo.loc_name}")
                    return gen_bus.loc_name
        
        # If no transformer is found or it does not meet the standard, use a direct connection
        app.PrintInfo(f"Generator {generator.loc_name} connected directly to the bus {gen_bus.loc_name}")
        return gen_bus.loc_name
        
    except Exception as e:
        app.PrintWarn(f"Error determining evaluation bus for {generator.loc_name}: {str(e)}")
        # Fallback: use the generator's direct bus
        if hasattr(generator, 'bus1') and generator.bus1.cterm:
            return generator.bus1.cterm.loc_name
        return None

# === Function to obtain the impedance between two nodes ===
def get_impedance_between_nodes(node1_name, node2_name):
    """Obtains the impedance between two nodes from the data loaded from the CSV"""
    # Extract numbers from bus names
    node1_num = extract_bus_number(node1_name)
    node2_num = extract_bus_number(node2_name)
    
    key = (node1_num, node2_num)
    if key in impedance_data:
        return impedance_data[key]
    else:
        app.PrintInfo(f"No impedance was found between {node1_name} ({node1_num}) y {node2_name} ({node2_num}) in the CSV")
        return float('inf')

# === Load flow configuration ===
ldf = app.GetFromStudyCase("ComLdf")
if ldf is None:
    raise RuntimeError("ComLdf was not found in the study")

def test_allocation_simple(p1_kw, p2_kw, g1, g2, min_pu=0.9):
    """
    Simplified function to test a power allocation.
    Returns feasibility, the minimum voltage, and the critical bus.
    """
    # Save original values
    p1_orig = g1.pgini
    p2_orig = g2.pgini
    
    # Assign new active power values
    g1.pgini = p1_kw
    g2.pgini = p2_kw
    
    # Run load flow
    err = ldf.Execute()
    converged = (err == 0)
    
    # Obtain minimum tension
    u_min = None
    bus_critico = None
    
    if converged:
        buses = app.GetCalcRelevantObjects("*.ElmTerm") or []
        for b in buses:
            try:
                u = b.GetAttribute("m:u")
                if u is not None:
                    if u_min is None or u < u_min:
                        u_min = u
                        bus_critico = b.loc_name
            except Exception:
                continue
    
    # Restore original values
    g1.pgini = p1_orig
    g2.pgini = p2_orig
    
    # Verify feasibility
    if not converged or u_min is None:
        return False, None, None
    
    feasible = u_min >= min_pu
    return feasible, u_min, bus_critico

# === ENHANCED FUNCTION TO FIND THE LIMIT WHERE U = 0.9 p.u. ===
def find_limit_at_voltage(g1, g2, fixed_p, fixed_gen, target_voltage=0.9):
    """
    Find the exact limit where minimum voltage = target_voltage.
    Use linear interpolation between feasible and infeasible points.

    """
    if fixed_gen == g1:
        # We are looking for a P2 for a permanent P1 position.
        p1_fixed = fixed_p
        
        # First, find two points: one with U > target and another with U < target.
        low_power = 0
        high_power = P_MAX * 1000
        low_voltage = None
        high_voltage = None
        crit_bus = None
        
        # Find a starting point with U > target_voltage
        for p_test in range(0, int(high_power), P_STEP * 1000):
            feasible, voltage, bus = test_allocation_simple(p1_fixed, p_test, g1, g2, target_voltage)
            
            if voltage is not None:
                crit_bus = bus
                if voltage > target_voltage:
                    low_power = p_test
                    low_voltage = voltage
                else:
                    high_power = p_test
                    high_voltage = voltage
                    break
        
        # If both points are found, perform linear interpolation
        if low_voltage is not None and high_voltage is not None and low_voltage > target_voltage > high_voltage:
            # Linear interpolation to find P where U = target_voltage
            delta_p = high_power - low_power
            delta_v = high_voltage - low_voltage
            
            if delta_v != 0:
                # Linear interpolation formula
                p_at_target = low_power + (target_voltage - low_voltage) * (delta_p / delta_v)
                
                # Verify the interpolated point
                feasible_target, voltage_target, bus_target = test_allocation_simple(
                    p1_fixed, p_at_target, g1, g2, target_voltage
                )
                
                if voltage_target is not None:
                    # Adjust iteratively if necessary
                    if abs(voltage_target - target_voltage) > 0.001:
                        # Refined binary search
                        p_low = low_power if voltage_target > target_voltage else p_at_target
                        p_high = p_at_target if voltage_target > target_voltage else high_power
                        
                        for _ in range(10):  # Maximum of 10 iterations
                            p_mid = (p_low + p_high) / 2
                            feasible_mid, voltage_mid, bus_mid = test_allocation_simple(
                                p1_fixed, p_mid, g1, g2, target_voltage
                            )
                            
                            if voltage_mid is None:
                                break
                                
                            if abs(voltage_mid - target_voltage) < 0.001:
                                return p_mid, voltage_mid, bus_mid
                            elif voltage_mid > target_voltage:
                                p_low = p_mid
                            else:
                                p_high = p_mid
                        
                        p_at_target = (p_low + p_high) / 2
                        feasible_target, voltage_target, bus_target = test_allocation_simple(
                            p1_fixed, p_at_target, g1, g2, target_voltage
                        )
                    
                    return p_at_target, voltage_target, bus_target
        
        # If interpolation was not possible, look for the last feasible point
        best_p = 0
        best_v = None
        best_bus = None
        
        for p_test in range(0, int(P_MAX * 1000), P_STEP * 1000):
            feasible, voltage, bus = test_allocation_simple(p1_fixed, p_test, g1, g2, target_voltage)
            
            if voltage is not None:
                if feasible:
                    best_p = p_test
                    best_v = voltage
                    best_bus = bus
                else:
                    # We found an infeasible point after a feasible one
                    if best_p > 0:
                        # Perform a binary search between the last feasible solution and this infeasible one
                        p_low = best_p
                        p_high = p_test
                        
                        for _ in range(8):
                            p_mid = (p_low + p_high) / 2
                            feasible_mid, voltage_mid, bus_mid = test_allocation_simple(
                                p1_fixed, p_mid, g1, g2, target_voltage
                            )
                            
                            if voltage_mid is None:
                                break
                                
                            if feasible_mid:
                                best_p = p_mid
                                best_v = voltage_mid
                                best_bus = bus_mid
                                p_low = p_mid
                            else:
                                p_high = p_mid
                        
                        return best_p, best_v, best_bus
                    else:
                        # There were no feasible points
                        break
        
        return best_p, best_v, best_bus
    
    else:  # fixed_gen == g2
        # We are looking for P1 for a permanent P2 role (similar logic)
        p2_fixed = fixed_p
        
        # Find points for interpolation
        low_power = 0
        high_power = P_MAX * 1000
        low_voltage = None
        high_voltage = None
        crit_bus = None
        
        for p_test in range(0, int(high_power), P_STEP * 1000):
            feasible, voltage, bus = test_allocation_simple(p_test, p2_fixed, g1, g2, target_voltage)
            
            if voltage is not None:
                crit_bus = bus
                if voltage > target_voltage:
                    low_power = p_test
                    low_voltage = voltage
                else:
                    high_power = p_test
                    high_voltage = voltage
                    break
        
        # Linear interpolation
        if low_voltage is not None and high_voltage is not None and low_voltage > target_voltage > high_voltage:
            delta_p = high_power - low_power
            delta_v = high_voltage - low_voltage
            
            if delta_v != 0:
                p_at_target = low_power + (target_voltage - low_voltage) * (delta_p / delta_v)
                
                feasible_target, voltage_target, bus_target = test_allocation_simple(
                    p_at_target, p2_fixed, g1, g2, target_voltage
                )
                
                if voltage_target is not None:
                    if abs(voltage_target - target_voltage) > 0.001:
                        p_low = low_power if voltage_target > target_voltage else p_at_target
                        p_high = p_at_target if voltage_target > target_voltage else high_power
                        
                        for _ in range(10):
                            p_mid = (p_low + p_high) / 2
                            feasible_mid, voltage_mid, bus_mid = test_allocation_simple(
                                p_mid, p2_fixed, g1, g2, target_voltage
                            )
                            
                            if voltage_mid is None:
                                break
                                
                            if abs(voltage_mid - target_voltage) < 0.001:
                                return p_mid, voltage_mid, bus_mid
                            elif voltage_mid > target_voltage:
                                p_low = p_mid
                            else:
                                p_high = p_mid
                        
                        p_at_target = (p_low + p_high) / 2
                        feasible_target, voltage_target, bus_target = test_allocation_simple(
                            p_at_target, p2_fixed, g1, g2, target_voltage
                        )
                    
                    return p_at_target, voltage_target, bus_target
        
        # Alternative search
        best_p = 0
        best_v = None
        best_bus = None
        
        for p_test in range(0, int(P_MAX * 1000), P_STEP * 1000):
            feasible, voltage, bus = test_allocation_simple(p_test, p2_fixed, g1, g2, target_voltage)
            
            if voltage is not None:
                if feasible:
                    best_p = p_test
                    best_v = voltage
                    best_bus = bus
                else:
                    if best_p > 0:
                        p_low = best_p
                        p_high = p_test
                        
                        for _ in range(8):
                            p_mid = (p_low + p_high) / 2
                            feasible_mid, voltage_mid, bus_mid = test_allocation_simple(
                                p_mid, p2_fixed, g1, g2, target_voltage
                            )
                            
                            if voltage_mid is None:
                                break
                                
                            if feasible_mid:
                                best_p = p_mid
                                best_v = voltage_mid
                                best_bus = bus_mid
                                p_low = p_mid
                            else:
                                p_high = p_mid
                        
                        return best_p, best_v, best_bus
                    else:
                        break
        
        return best_p, best_v, best_bus

# === Calculate evenly distributed points ===
def calculate_distributed_points(num_points):
    """
    Calculate the P1 values ​​distributed evenly from the known point to the opposite point.
    
    """
    if num_points < 2:
        return [KNOWN_POINT["P1_MW"], OPPOSITE_POINT["P1_MW"]]
    
    # Create a linearly spaced array from P1_start to P1_end
    p1_start = KNOWN_POINT["P1_MW"]
    p1_end = OPPOSITE_POINT["P1_MW"]
    
    # Generate evenly distributed points
    p1_values = np.linspace(p1_start, p1_end, num_points)
    
    # Round to one decimal place for greater clarity
    p1_values = [round(p, 1) for p in p1_values]
    
    app.PrintInfo(f"\nDistribución de {num_points} puntos:")
    app.PrintInfo(f"P1 conocido: {p1_start} MW")
    app.PrintInfo(f"P1 opuesto: {p1_end} MW")
    app.PrintInfo(f"Puntos P1: {p1_values}")
    
    return p1_values

# === Find distributed points ===
def find_distributed_boundary_points(g1, g2, num_points):
    """
    Find points distributed evenly along the stability boundary.
    
    """
    boundary_points = []
    
    # Calculate distributed P1 values
    p1_values = calculate_distributed_points(num_points)
    
    app.PrintInfo(f"\nBuscando {len(p1_values)} puntos en la frontera...")
    
    # For each value of P1, find the corresponding P2 where U = MIN_VOLTAGE
    for i, p1 in enumerate(p1_values):
        p1_kw = p1 * 1000
        
        app.PrintInfo(f"\n[{i+1}/{len(p1_values)}] Buscando P2 para P1={p1} MW:")
        
        # Find the corresponding P2
        p2_kw, voltage, bus_crit = find_limit_at_voltage(
            g1, g2, p1_kw, g1, target_voltage=MIN_VOLTAGE
        )
        
        if p2_kw > 0 and voltage is not None:
            # Verify that the voltage is close to the target
            if abs(voltage - MIN_VOLTAGE) < 0.02:  # 0.02 p.u. of tolerance
                # Obtain evaluation buses
                eval_bus1 = get_evaluation_bus_for_generator(g1)
                eval_bus2 = get_evaluation_bus_for_generator(g2)
                
                point_data = {
                    "P1_MW": p1,
                    "P2_MW": p2_kw / 1000,
                    "Bus_Critico": bus_crit,
                    "U_Critico_pu": voltage,
                    "Bus_G1": eval_bus1,
                    "Bus_G2": eval_bus2,
                    "Anomalia_Detectada": "NO",
                    "Indice": i+1
                }
                
                boundary_points.append(point_data)
                
                app.PrintInfo(f"✓ Punto {i+1}: P1={p1} MW → P2={p2_kw/1000:.1f} MW (U={voltage:.4f} p.u.)")
            else:
                app.PrintWarn(f"✗ Punto {i+1}: P1={p1} MW → P2={p2_kw/1000:.1f} MW (U={voltage:.4f} p.u., fuera de tolerancia)")
        else:
            app.PrintWarn(f"✗ Punto {i+1}: P1={p1} MW → No se encontró límite")
    
    return boundary_points

# === Function to filter out unwanted points ===
def filter_boundary_points(points):
    """Filters out unwanted points but retains valid endpoints."""
    filtered = []
    points = [p for p in points if not ((p['P1_MW'] == 0 and p['P2_MW'] > 0) or (p['P2_MW'] == 0 and p['P1_MW'] > 0))]
    points.sort(key=lambda x: x['P1_MW'])
    
    prev_p1 = None
    for p in points:
        if prev_p1 is not None and p['P1_MW'] == prev_p1:
            if p['P2_MW'] > filtered[-1]['P2_MW']:
                filtered[-1] = p
        else:
            filtered.append(p)
        prev_p1 = p['P1_MW']
    return filtered

# === Function to execute the complete analysis ===
def run_stability_analysis(contingency_name=None, contingency_element=None):
    """Perform the complete stability analysis for a given condition"""
    
    # Apply contingency if specified
    original_status = None
    if contingency_element:
        try:
            original_status = contingency_element.outserv
            contingency_element.outserv = 1  #  Take item out of service
            app.PrintInfo(f"Applying contingency measures: {contingency_name} - {contingency_element.loc_name}")
            # Run a load flow to stabilize the network following the contingency
            ldf.Execute()
        except Exception as e:
            app.PrintError(f"Error applying contingency: {str(e)}")
            return
    
    # === Find electrically close pairs ===
    pairs_close = []
    for g1, g2 in itertools.combinations(gen_nonsync, 2):
        try:
            # Obtain the evaluation nodes for both generators
            node1 = get_evaluation_bus_for_generator(g1)
            node2 = get_evaluation_bus_for_generator(g2)
            
            if not node1 or not node2:
                app.PrintInfo(f"Skipping a pair {g1.loc_name} - {g2.loc_name} (Could not retrieve evaluation nodes)")
                continue
            
            # Obtain node-to-node impedance from the CSV
            z_ij = get_impedance_between_nodes(node1, node2)
            node1_num = extract_bus_number(node1)
            node2_num = extract_bus_number(node2)
            app.PrintInfo(f"Impedance {g1.loc_name} ({node1} [{node1_num}]) - {g2.loc_name} ({node2} [{node2_num}]): |Z| = {z_ij:.6f}")
            
            if z_ij >= Z_THRESHOLD:
                pairs_close.append((g1, g2, round(z_ij, 6)))
                app.PrintInfo(f"  → NEARBY PAIR (|Z| = {z_ij:.6f} >= {Z_THRESHOLD})")
            else:
                app.PrintInfo(f"  → Non-adjacent pair (|Z| = {z_ij:.6f} < {Z_THRESHOLD})")
                
        except Exception as e:
            app.PrintError(f"Error calculating impedance between {g1.loc_name} and {g2.loc_name}: {str(e)}")
            continue

    if not pairs_close:
        app.PrintInfo(f"No electrically close pairs were found (|Z| >= {Z_THRESHOLD}).")
        # Restore item if it was a contingency
        if contingency_element and original_status is not None:
            contingency_element.outserv = original_status
            ldf.Execute()
        return

    # === Analysis of close peers ===
    all_boundary_data = []

    for g1, g2, z_ij in pairs_close:
        node1 = get_evaluation_bus_for_generator(g1)
        node2 = get_evaluation_bus_for_generator(g2)
        app.PrintInfo(f"\n{'='*60}")
        app.PrintInfo(f"Analyzing the pair: {g1.loc_name} (Bus: {node1}) - {g2.loc_name} (Bus: {node2})")
        app.PrintInfo(f"Impedance: |Z| = {z_ij:.6f}")
        app.PrintInfo(f"Known starting point: P1={KNOWN_POINT['P1_MW']} MW, P2={KNOWN_POINT['P2_MW']} MW")
        app.PrintInfo(f"Objective endpoint: P1={OPPOSITE_POINT['P1_MW']} MW, P2={OPPOSITE_POINT['P2_MW']} MW")
        app.PrintInfo(f"Number of points to extract: {NUM_POINTS}")
        app.PrintInfo(f"Looking for points where U_min = {MIN_VOLTAGE} p.u.")
        app.PrintInfo(f"{'='*60}")
        
        # === Use the new function for distributed points ===
        boundary_points = find_distributed_boundary_points(g1, g2, NUM_POINTS)
        
        # Verificar que tenemos datos
        if not boundary_points:
            app.PrintWarn(f"No points were found for the pair {g1.loc_name}-{g2.loc_name}")
            continue
        
        # Ensure that we have the known point and the opposite one
        known_found = False
        opposite_found = False
        
        for point in boundary_points:
            if (abs(point["P1_MW"] - KNOWN_POINT["P1_MW"]) < 0.1 and 
                abs(point["P2_MW"] - KNOWN_POINT["P2_MW"]) < 0.1):
                known_found = True
            if (abs(point["P1_MW"] - OPPOSITE_POINT["P1_MW"]) < 0.1 and 
                abs(point["P2_MW"] - OPPOSITE_POINT["P2_MW"]) < 0.1):
                opposite_found = True
        
        # Add missing points if necessary
        if not known_found:
            # Verify the known point directly
            feasible, voltage, bus_crit = test_allocation_simple(
                KNOWN_POINT["P1_MW"] * 1000, 
                KNOWN_POINT["P2_MW"] * 1000, 
                g1, g2, MIN_VOLTAGE
            )
            
            if voltage is not None:
                eval_bus1 = get_evaluation_bus_for_generator(g1)
                eval_bus2 = get_evaluation_bus_for_generator(g2)
                
                boundary_points.append({
                    "P1_MW": KNOWN_POINT["P1_MW"],
                    "P2_MW": KNOWN_POINT["P2_MW"],
                    "Bus_Critico": bus_crit,
                    "U_Critico_pu": voltage,
                    "Bus_G1": eval_bus1,
                    "Bus_G2": eval_bus2,
                    "Anomalia_Detectada": "NO",
                    "Indice": 0
                })
        
        if not opposite_found:
            # Look for the opposite point
            app.PrintInfo(f"\nLooking for the opposite point: P1={OPPOSITE_POINT['P1_MW']} MW")
            p1_kw = OPPOSITE_POINT["P1_MW"] * 1000
            p2_kw, voltage, bus_crit = find_limit_at_voltage(
                g1, g2, p1_kw, g1, target_voltage=MIN_VOLTAGE
            )
            
            if p2_kw > 0 and voltage is not None:
                eval_bus1 = get_evaluation_bus_for_generator(g1)
                eval_bus2 = get_evaluation_bus_for_generator(g2)
                
                boundary_points.append({
                    "P1_MW": OPPOSITE_POINT["P1_MW"],
                    "P2_MW": p2_kw / 1000,
                    "Bus_Critico": bus_crit,
                    "U_Critico_pu": voltage,
                    "Bus_G1": eval_bus1,
                    "Bus_G2": eval_bus2,
                    "Anomalia_Detectada": "NO",
                    "Indice": NUM_POINTS + 1
                })
        
        # Filter and sort points
        unique_data = {}
        for point in boundary_points:
            key = (round(point["P1_MW"], 1), round(point["P2_MW"], 1))
            unique_data[key] = point
        
        sorted_data = sorted(unique_data.values(), key=lambda x: x["P1_MW"])
        filtered_data = filter_boundary_points(sorted_data)
        
        if not filtered_data:
            app.PrintWarn(f"No points remained after filtering for {g1.loc_name}-{g2.loc_name}")
            continue
        
        filtered_data.sort(key=lambda x: x['P1_MW'])
        
        # Save data for this pair
        pair_data = {
            "Gen1": g1.loc_name,
            "Gen2": g2.loc_name,
            "Bus1": node1,
            "Bus2": node2,
            "Impedancia_Z": z_ij,
            "Num_Puntos_Solicitados": NUM_POINTS,
            "Puntos_Encontrados": len(filtered_data),
            "Boundary_Points": filtered_data
        }
        all_boundary_data.append(pair_data)
        
        app.PrintInfo(f"\n{'='*60}")
        app.PrintInfo(f"SUMMARY for {g1.loc_name}-{g2.loc_name}:")
        app.PrintInfo(f"- Requested points: {NUM_POINTS}")
        app.PrintInfo(f"- Conflicting points: {len(filtered_data)}")
        if filtered_data:
            app.PrintInfo(f"- P1 initial: {filtered_data[0]['P1_MW']:.1f} MW, P2: {filtered_data[0]['P2_MW']:.1f} MW")
            app.PrintInfo(f"- P1 final: {filtered_data[-1]['P1_MW']:.1f} MW, P2: {filtered_data[-1]['P2_MW']:.1f} MW")
            app.PrintInfo(f"- Average voltage: {sum(p['U_Critico_pu'] for p in filtered_data)/len(filtered_data):.4f} p.u.")
        app.PrintInfo(f"{'='*60}")

    # === Export results ===
    base_folder = EXPORT_PATH
    if contingency_name:
        base_folder = os.path.join(EXPORT_PATH, f"N-1_{contingency_name}")
        os.makedirs(base_folder, exist_ok=True)
    
    for pair in all_boundary_data:
        if not pair["Boundary_Points"]:
            continue
            
        pair_folder = os.path.join(EXPORT_PATH, f"CAP_{g1.loc_name}_{g2.loc_name}")
        os.makedirs(pair_folder, exist_ok=True)
        
        # Exportar CSV
        csv_filename = f"{EXAMPLE}_CAP_{g1.loc_name}_{g2.loc_name}.csv"
        csv_path = os.path.join(pair_folder, csv_filename)
        
        fieldnames = [
            "Indice", "P1_MW", "P2_MW",
            "Bus_Critico", "U_Critico_pu",
            "Bus_G1", "Bus_G2",
            "Anomalia_Detectada"
        ]
        
        with open(csv_path, "w", newline="", encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            for point in pair["Boundary_Points"]:
                writer.writerow(point)
        
        # Generate graphs
        plt.figure(figsize=(12, 8))
        p1_values = [p["P1_MW"] for p in pair["Boundary_Points"]]
        p2_values = [p["P2_MW"] for p in pair["Boundary_Points"]]
        voltages = [p["U_Critico_pu"] for p in pair["Boundary_Points"]]
        indices = [p.get("Indice", i+1) for i, p in enumerate(pair["Boundary_Points"])]
        
        # Plot the main line
        plt.plot(p1_values, p2_values, 'b-', linewidth=2, label='Frontera de estabilidad')
        
        # Mark individual points with labels
        scatter = plt.scatter(p1_values, p2_values, c=voltages, cmap='RdYlGn', 
                             s=150, edgecolors='black', alpha=0.8,
                             vmin=MIN_VOLTAGE-0.02, vmax=MIN_VOLTAGE+0.02)
        
        # Label some important points
        if len(p1_values) > 0:
            # Starting point (known)
            plt.annotate(f"Inicio\nP1={p1_values[0]:.1f}\nP2={p2_values[0]:.1f}", 
                        (p1_values[0], p2_values[0]), 
                        xytext=(10, 10), textcoords='offset points',
                        bbox=dict(boxstyle='round,pad=0.3', facecolor='lightgreen', alpha=0.8),
                        fontsize=9)
            
            # End point (opposite)
            plt.annotate(f"Fin\nP1={p1_values[-1]:.1f}\nP2={p2_values[-1]:.1f}", 
                        (p1_values[-1], p2_values[-1]), 
                        xytext=(-10, -10), textcoords='offset points',
                        bbox=dict(boxstyle='round,pad=0.3', facecolor='lightcoral', alpha=0.8),
                        fontsize=9)
        
        # Configure graphics
        plt.xlabel(f"Potencia {pair['Gen1']} (MW)", fontsize=14, fontweight='bold')
        plt.ylabel(f"Potencia {pair['Gen2']} (MW)", fontsize=14, fontweight='bold')
        
        title_lines = [
            f"Stability Boundary - {pair['Num_Puntos_Solicitados']} points",
            f"{pair['Gen1']} vs {pair['Gen2']}",
            f"|Z| = {pair['Impedancia_Z']:.6f}, Tensión Mínima 0.9 pu"
        ]
        
        if contingency_name:
            title_lines.append(f"Contingency: {contingency_name}")
        
        plt.title("\n".join(title_lines), fontsize=16, fontweight='bold', pad=20)
        
        plt.grid(True, linestyle='--', alpha=0.7)
        
        info_text = f"Pointss: {pair['Puntos_Encontrados']}/{pair['Num_Puntos_Solicitados']}\n"
        info_text += f"Threshold: {MIN_VOLTAGE} p.u.\n"
        info_text += f"U_avg: {sum(voltages)/len(voltages):.4f} p.u."
        
        plt.text(0.02, 0.98, info_text, transform=plt.gca().transAxes,
                fontsize=10, verticalalignment='top',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))
        
        plt.tight_layout()
        
        plot_filename = f"boundary_plot_{pair['Gen1']}_{pair['Gen2']}.png"
        plot_path = os.path.join(pair_folder, plot_filename)
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        plt.close()
        
        app.PrintInfo(f"\nResults for {pair['Gen1']}-{pair['Gen2']}:")
        app.PrintInfo(f" - CSV saved to: {csv_path}")
        app.PrintInfo(f" - Graph saved in: {plot_path}")

    # Restore item if it was a contingency
    if contingency_element and original_status is not None:
        try:
            contingency_element.outserv = original_status
            ldf.Execute()
            app.PrintInfo(f"Restoring element: {contingency_element.loc_name}")
        except Exception as e:
            app.PrintError(f"Error restoring item: {str(e)}")

    app.PrintInfo(f"\nAnalysis {'contingency ' + contingency_name if contingency_name else 'complete'}.")
    app.PrintInfo(f"Results in: {base_folder}")

# === MAIN EXECUTION ===

# 1. Run analysis under normal conditions
app.PrintInfo("="*60)
app.PrintInfo("RUNNING ANALYSIS UNDER NORMAL CONDITIONS")
app.PrintInfo("="*60)
app.PrintInfo(f"Voltage threshold: {MIN_VOLTAGE} p.u.")
app.PrintInfo(f"Number of points to extract: {NUM_POINTS}")
app.PrintInfo(f"Starting point: P1={KNOWN_POINT['P1_MW']} MW, P2={KNOWN_POINT['P2_MW']} MW")
app.PrintInfo(f"Final point: P1={OPPOSITE_POINT['P1_MW']} MW, P2={OPPOSITE_POINT['P2_MW']} MW")
app.PrintInfo("="*60)

try:
    run_stability_analysis()
except Exception as e:
    app.PrintError(f"Runtime error: {str(e)}")
    import traceback
    app.PrintError(traceback.format_exc())

# Restore original state
app.PrintInfo("\nRestoring the generators to their original state...")
for g in gen_nonsync:
    g.pgini = pgini_base[g]
ldf.Execute()

app.PrintInfo("\n" + "="*60)
app.PrintInfo("ANALYSIS COMPLETE")
app.PrintInfo("="*60)